import { StyleSheet } from "react-native";

export const modalStyle = new StyleSheet.create({
  loginModalUpperLayer: {
    backgroundColor: "white",
    flexDirection: "column",
    flex: 1,
    alignItems: "center",
  },
  loginModalWrapper: {
    paddingTop: 32,
    width: "100%",
  },
  loginInputDiv: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  loginButtonsBottom: {
    display: "flex",
    width: "100%",
    height: 60,
    paddingVertical: 10,
    paddingHorizontal: 8,
    paddingLeft: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#B0B0B0",
    borderStyle: "solid",
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  loginButtonsTop: {
    display: "flex",
    width: "100%",
    height: 60,
    paddingVertical: 10,
    paddingHorizontal: 8,
    paddingLeft: 14,
    alignItems: "center",
    borderWidth: 1,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: "#B0B0B0",
    padding: 20,
  },
  loginInputDivText: {
    paddingTop: 16,
    fontSize: 12,
    fontWeight: 400,
    lineHeight: "140%",
  },
  LoginBtn: {
    display: "flex",
    paddingHorizontal: 19,
    marginTop:26,
    marginBottom:32,
    paddingVertical: 24,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "#D53858",
  },
  horizontalLineWrapper:{
    flexDirection:'row',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom:40,
    gap: 8,
  },
  horizontalLine:{
    backgroundColor: '#DEDEDE',
    width: 154,
    height: 1,
  }
});
